from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.units import inch
from datetime import datetime
from io import BytesIO
from typing import List, Dict

class ReportGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self.title_style = ParagraphStyle(
            'CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=18,
            spaceAfter=30,
            alignment=1  # Center alignment
        )
        self.heading_style = ParagraphStyle(
            'CustomHeading',
            parent=self.styles['Heading2'],
            fontSize=14,
            spaceAfter=12
        )
    
    def generate_health_report(self, data: List[Dict], test_type: str, title: str, user_name: str) -> BytesIO:
        """Generate a PDF report for health data"""
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
        
        # Build the document content
        story = []
        
        # Title
        story.append(Paragraph(title, self.title_style))
        story.append(Spacer(1, 12))
        
        # Patient info
        story.append(Paragraph(f"Patient: {user_name}", self.heading_style))
        story.append(Paragraph(f"Report Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}", self.styles['Normal']))
        story.append(Spacer(1, 20))
        
        # Data table
        if data:
            table_data = self._prepare_table_data(data, test_type)
            table = Table(table_data)
            
            # Style the table
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 14),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 1), (-1, -1), 12),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            
            story.append(table)
        else:
            story.append(Paragraph("No data available for the selected period.", self.styles['Normal']))
        
        # Footer
        story.append(Spacer(1, 30))
        story.append(Paragraph("This report is generated by Health Monitor for Parents", self.styles['Italic']))
        story.append(Paragraph("Please consult with your healthcare provider for medical advice.", self.styles['Italic']))
        
        # Build PDF
        doc.build(story)
        buffer.seek(0)
        return buffer
    
    def _prepare_table_data(self, data: List[Dict], test_type: str) -> List[List[str]]:
        """Prepare data for table based on test type"""
        if test_type == "Weight":
            headers = ["Date", "Weight (kg)", "Status"]
            rows = [headers]
            for record in reversed(data):  # Most recent first
                date = record['test_sessions']['session_date']
                weight = f"{record['value_1']:.1f}"
                status = record['status']
                rows.append([date, weight, status])
        
        elif test_type == "Sugar":
            headers = ["Date", "Blood Sugar (mg/dL)", "Status"]
            rows = [headers]
            for record in reversed(data):
                date = record['test_sessions']['session_date']
                sugar = f"{record['value_1']:.0f}"
                status = record['status']
                rows.append([date, sugar, status])
        
        elif test_type == "Blood Pressure":
            headers = ["Date", "Systolic (mmHg)", "Diastolic (mmHg)", "Status"]
            rows = [headers]
            for record in reversed(data):
                date = record['test_sessions']['session_date']
                systolic = f"{record['value_1']:.0f}"
                diastolic = f"{record['value_2']:.0f}"
                status = record['status']
                rows.append([date, systolic, diastolic, status])
        
        elif test_type == "SpO2":
            headers = ["Date", "SpO2 (%)", "Pulse (BPM)", "Status"]
            rows = [headers]
            for record in reversed(data):
                date = record['test_sessions']['session_date']
                spo2 = f"{record['value_1']:.1f}"
                pulse = f"{record['value_2']:.0f}"
                status = record['status']
                rows.append([date, spo2, pulse, status])
        
        elif test_type == "Temperature":
            headers = ["Date", "Temperature (°C)", "Status"]
            rows = [headers]
            for record in reversed(data):
                date = record['test_sessions']['session_date']
                temp = f"{record['value_1']:.1f}"
                status = record['status']
                rows.append([date, temp, status])
        
        else:
            headers = ["Date", "Value", "Status"]
            rows = [headers]
            for record in reversed(data):
                date = record['test_sessions']['session_date']
                value = str(record['value_1'])
                status = record['status']
                rows.append([date, value, status])
        
        return rows